src/MainApp/Presentation/Restaurant.MainApp.Presentation/Pages/Order/Kitchen.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Restaurant.MainApp.Core.Application.Contract.ApplicationServices;
using Restaurant.MainApp.Core.Application.Contract.DTO.OrderHeader;

namespace Restaurant.MainApp.Presentation.Pages.Order
{
    [Authorize(Roles = "Admin,Kitchen")]
    public class KitchenModel : PageModel
    {
        private IApplicationOrder _applicationOrder { get; }
        private IApplicationStatus _applicationStatus { get; }
        private ChangeStatusOrder _changeStatusOrder { get; set; }
        public IEnumerable<OrderKitchen> OredrKitchens { get; set; }
        public KitchenModel(IApplicationOrder applicationOrder, IApplicationStatus applicationStatus)
        {
            _applicationOrder = applicationOrder;
            _applicationStatus = applicationStatus;
            _changeStatusOrder = new();
        }

        public async Task OnGet()
        {
            OredrKitchens = await _applicationOrder.GetOrderKitchen(_applicationStatus.StatusSubmitted);
        }

        public async Task<IActionResult> OnPostCook([FromQuery] string OrderNumber)
        {
            if (OrderNumber == null) return BadRequest();
            _changeStatusOrder.OrderId = OrderNumber;
            _changeStatusOrder.Status = _applicationStatus.StatusInProcess;
            await _applicationOrder.ChangeStatusOrderHeader(_changeStatusOrder);
            return RedirectToPage("./Kitchen");
        }

        public async Task<IActionResult> OnPostReady([FromQuery] string OrderNumber)
        {
            if (OrderNumber == null) return BadRequest();
            _changeStatusOrder.OrderId = OrderNumber;
            _changeStatusOrder.Status = _applicationStatus.StatusReady;
            await _applicationOrder.ChangeStatusOrderHeader(_changeStatusOrder);
            return RedirectToPage("./Kitchen");
        }
        public async Task<IActionResult> OnPostCancel([FromQuery] string OrderNumber)
        {
            if (OrderNumber == null) return BadRequest();
            _changeStatusOrder.OrderId = OrderNumber;
            _changeStatusOrder.Status = _applicationStatus.StatusCancelled;
            await _applicationOrder.ChangeStatusOrderHeader(_changeStatusOrder);
            return RedirectToPage("./Kitchen");
        }
    }
}

src/MainApp/Presentation/Restaurant.MainApp.Presentation/Pages/Order/OrderDetial.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Restaurant.MainApp.Core.Application.Contract.ApplicationServices;
using Restaurant.MainApp.Core.Application.Contract.DTO.OrderHeader;
using Restaurant.MainApp.Infrastructure.Tools.Tools;
using Stripe;

namespace Restaurant.MainApp.Presentation.Pages.Order
{
    [Authorize(Roles = "Admin,FrontDesk")]
    public class OrderDetialModel : PageModel
    {
        private StripPayment strip { get; }
        private IApplicationOrder _applicationOrder { get; }
        private IApplicationStatus _applicationStatus { get; }
        private ChangeStatusOrder _changeStatus { get; set; }
        public GetOrderHeader? OrderHeader { get; set; }

        public IEnumerable<GetOrderDetails> OrderDetails { get; set; }

        public OrderDetialModel(IOptions<StripPayment> strip,IApplicationOrder applicationOrder, IApplicationStatus applicationStatus)
        {
            _applicationOrder = applicationOrder;
            _applicationStatus = applicationStatus;
            OrderHeader = new();
            _changeStatus = new();
            this.strip = strip.Value;
        }

        public async Task<IActionResult> OnGet([FromQuery] string OrderNumber)
        {
            if(OrderNumber == null) return BadRequest();
            
            OrderHeader = await _applicationOrder.GetOrderHeader(OrderNumber);
            OrderDetails = await _applicationOrder.GetOrderDetails(OrderNumber);
            return Page();
        }

        public async Task<IActionResult> OnGetOrderCompleted([FromQuery] string Ordernumber)
        {
            if(Ordernumber==null) return BadRequest();
            _changeStatus.Status = _applicationStatus.StatusCompleted;
            _changeStatus.OrderId = Ordernumber;
            await _applicationOrder.ChangeStatusOrderHeader(_changeStatus);
            return RedirectToPage("./OrderList");
        }
        public async Task<IActionResult> OnGetCancellOrder([FromQuery] string OrderNumber)
        {
            if (OrderNumber == null) return BadRequest();
            _changeStatus.OrderId=OrderNumber;
            _changeStatus.Status = _applicationStatus.StatusCancelled;
            await _applicationOrder.ChangeStatusOrderHeader(_changeStatus);
            return RedirectToPage("./OrderList");
        }

        public async Task<IActionResult> OnGetRefundOrder([FromQuery] string OrderNumber)
        {
            var order = await _applicationOrder.GetOrderHeader(OrderNumber);
            StripeConfiguration.ApiKey = strip.SecretKey;

            var options = new RefundCreateOptions
            {
                Reason = RefundReasons.RequestedByCustomer,
                PaymentIntent = order.PaymentIntentId
            };

            var service = new RefundService();
            Refund refund = service.Create(options);
            _changeStatus.OrderId = OrderNumber;
            _changeStatus.Status = _applicationStatus.StatusRefunded;
           await _applicationOrder.ChangeStatusOrderHeader(_changeStatus);
            return RedirectToPage("OrderList");
        }
    }
    
}

src/MainApp/Presentation/Restaurant.MainApp.Presentation/Pages/Order/OrderList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Restaurant.MainApp.Core.Application.Contract.ApplicationServices;
using Restaurant.MainApp.Core.Application.Contract.DTO.OrderHeader;

namespace Restaurant.MainApp.Presentation.Pages.Order
{
    [Authorize(Roles = "Admin,FrontDesk")]
    public class OrderListModel : PageModel
    {
        private IApplicationOrder _applicationOrder { get; }
        private  IApplicationStatus _applicationStatus { get; }
        public IEnumerable<GetOrderList> OrderList { get; set; }
        public OrderListModel(IApplicationOrder applicationOrder, IApplicationStatus applicationStatus)
        {
            _applicationOrder = applicationOrder;
            _applicationStatus = applicationStatus;
        }

        
        public async Task OnGet([FromQuery] string? status)
        {

            if (status == "cancelled")
            {
                OrderList = await _applicationOrder.GetOrderHeaderList(_applicationStatus.StatusCancelled);
            }
            else
            {
                if (status == "completed")
                {
                    OrderList = await _applicationOrder.GetOrderHeaderList(_applicationStatus.StatusCompleted);
                }
                else
                {
                    if (status == "ready")
                    {
                        OrderList = await _applicationOrder.GetOrderHeaderList(_applicationStatus.StatusReady);
                    }
                    
                    else
                    {
                        if (status == "InProcess")
                        {
                            OrderList= await _applicationOrder.GetOrderHeaderList(_applicationStatus.StatusInProcess);
                        }
                        else
                            OrderList = await _applicationOrder.GetOrderHeaderList(_applicationStatus.StatusSubmitted);
                    }
                }
            }
        }
    }
}

src/MainApp/Presentation/Restaurant.MainApp.Presentation/Pages/Order/Kitchen.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Restaurant.MainApp.Core.Application.Contract.ApplicationServices
@model Restaurant.MainApp.Presentation.Pages.Order.KitchenModel
@{
}
@inject IApplicationStatus Status

<h1 class="text-primary py-3">Manage Order's</h1>
<form method="post">
    <div class="container row bg-white p-2 mb-3 rounded">
        @foreach (var item in Model.OredrKitchens)
        {
            <div class="col-12 pb-3 pt-3 mt-4 border  rounded">
                <div class="row">
                    <div class="col-4">
                        Order Number : @item.OrderList.Name
                       
                        <ul class="text-info">
                        @foreach (var det in item.OrderDetails)
                        {
                            <li>@det.FoodName x @det.Count</li>
                        }
                        </ul>
                       
                    </div>
                    <div class="col-4 pb-2">
                        <div class="input-group pb-2">
                            <div class="input-group-append">
                                <span class="input-group-text bg-secondary border">Time</span>
                            </div>
                            <input type="text" class="form-control" readonly  value="@item.OrderList.PickupTime"/>
                        </div>
                        <textarea readonly class="rounded border form-control" rows="3">@item.OrderList.Comment</textarea>
                    </div>
                    <div class="col-3 offset-1 d-flex align-content-center">
                        <div class="col-12">

                            @if (item.OrderList.Status == Status.StatusSubmitted)
                            {
                                <button asp-page-handler="Cook" asp-route-OrderNumber="@item.OrderList.OrderNumber" type="submit" class="btn btn-primary form-control mb-3">
                                    <i class="bi bi-check-square"></i> &nbsp; Start Cooking
                                </button>

                            }
                           @if (item.OrderList.Status == Status.StatusInProcess)
                           {
                                <button asp-page-handler="Ready" asp-route-OrderNumber="@item.OrderList.OrderNumber" type="submit" class="btn btn-success form-control mb-3">
                                   <i class="bi bi-emoji-laughing"></i> &nbsp; Order Ready
                               </button>
                           }

                            <button asp-page-handler="Cancel" asp-route-OrderNumber="@item.OrderList.OrderNumber" type="submit" class="btn btn-warning form-control mb-3">
                                <i class="bi bi-x-square-fill"></i> &nbsp; Cancel Order
                            </button>

                        </div>
                    </div>
                </div>
            </div>
        }
 

    </div>

</form>

src/MainApp/Presentation/Restaurant.MainApp.Presentation/Pages/Order/OrderDetial.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Restaurant.MainApp.Core.Application.Contract.ApplicationServices
@model Restaurant.MainApp.Presentation.Pages.Order.OrderDetialModel
@inject IApplicationStatus Status
    <div class="border p-4 ml-1 backgroundWhite mt-4">
        <div class="row pb-1">
            <div class="col-12 col-md-6 ">
                <p class="h2  text-primary">Order Details</p>
            </div>
            <div class="col-12 col-md-4 offset-md-2">
                <a class="btn btn-outline-primary form-control" asp-page="/Order/OrderList">Back to Orders </a>
            </div>
        </div>
        <hr />

        <div class="row pt-2">

            <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">

                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Name
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderHeader!.Name"/>
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Email
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderHeader!.Email" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Phone Number
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderHeader!.PhoneNumber" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Order Total
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderHeader!.OrderTotal" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Order Date Time
                    </div>
                    <div class="col-md-9 col-12">
                        <input disabled class="form-control" asp-for="OrderHeader!.PickupTime!" />
                    </div>
                </div>
                <div class="form-group row py-1">
                    <div class="col-md-3 col-12 text-primary">
                        Comments
                    </div>
                    <div class="col-md-9 col-12">
                        <textarea disabled class="form-control" rows="3">@Model.OrderHeader!.Comment</textarea>
                    </div>
                </div>

            </div>

            <div class="col-lg-4 col-12">
                <button type="submit" disabled class="btn btn-outline-info form-control">@Model.OrderHeader.status</button>

                <h4 class="d-flex justify-content-between align-content-center mb-3">
                    <span class="text-muted">Order ID: @Model.OrderHeader.OrderNumber</span>
                </h4>
                <ul class="list-group mb-3">
                    @foreach (var item in Model.OrderDetails)
                    {
                        <li class="list-group-item d-flex justify-content-between">
                            <div>
                                <h6 class="my-0">@item.FoodName</h6>
                                <small class="text-muted">Quantity : @item.Count</small>
                            </div>
                            <span class="text-muted">$@(Convert.ToDouble(item.Price) * Convert.ToDouble(item.Count))</span>
                        </li>

                    }


                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <span class="text-info"> Total (USD)</span>
                        <strong class="text-info">$@Model.OrderHeader.OrderTotal</strong>
                    </li>

                </ul>
                @if (Model.OrderHeader.status == Status.StatusReady)
                {
                    <div class="col-12 pb-2">
                        <a type="submit" class="btn btn-primary form-control"
                                asp-page-handler="OrderCompleted" asp-route-OrderNumber="@Model.OrderHeader.OrderNumber">
                            Complete Order
                        </a>
                    </div>
                }
                @if (Model.OrderHeader.status == Status.StatusReady || Model.OrderHeader.status == Status.StatusSubmitted || Model.OrderHeader.status == Status.StatusInProcess)
                {
                    <div class="row pt-3">
                        <div class="col-6">
                            <a asp-page-handler="CancellOrder" asp-route-OrderNumber="@Model.OrderHeader.OrderNumber" class="btn btn-warning form-control"><i class="bi bi-x-square"></i> Cancel Order</a>
                        </div>
                        <div class="col-6">
                        <a asp-page-handler="RefundOrder" asp-route-OrderNumber="@Model.OrderHeader.OrderNumber" class="btn btn-danger form-control"><i class="bi bi-currency-dollar"></i>Refund Order</a>
                        </div>
                    </div>
                }

            </div>

        </div>
    </div>

src/MainApp/Presentation/Restaurant.MainApp.Presentation/Pages/Order/OrderList.cshtml
@page
@model Restaurant.MainApp.Presentation.Pages.Order.OrderListModel
@{
    var classAttributeCancelled = String.Empty;
    var classAttributeCompleted = String.Empty;
    var classAttributeReady = String.Empty;
    var classAttributeInProcess = String.Empty;
    var classAttributeDeafult = String.Empty;
    var status = HttpContext.Request.Query["status"];
    if (String.IsNullOrWhiteSpace(status))
    {
        classAttributeDeafult = "active text-white";
    }
    else
    {
        if (status == "cancelled") { classAttributeCancelled = "active text-white"; }
        if (status == "InProcess") { classAttributeInProcess = "active text-white"; }
        else if (status == "completed") { classAttributeCompleted = "active text-white"; }
        else if (status == "ready") { classAttributeReady = "active text-white"; }
    }
}
<div class="container p-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h2 class="text-primary">Order List</h2>
        </div>
        <div class="p-2" >
            <ul class="list-group list-group-horizontal-sm">
                <a style="text-decoration:none;"  asp-page="OrderList" asp-route-status="cancelled">
                <li class="list-group-item @classAttributeCancelled" >Cancelled</li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList" asp-route-status="completed">
                <li class="list-group-item @classAttributeCompleted" >Completed</li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList" asp-route-status="ready">
                <li class="list-group-item @classAttributeReady" >Ready For PickUp</li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList" asp-route-status="InProcess">
                    <li class="list-group-item @classAttributeInProcess" >InProcess</li>
                </a>
                <a style="text-decoration:none;" asp-page="OrderList" >
                <li class="list-group-item @classAttributeDeafult" >Submited</li>
                </a>
            </ul>
        </div>
    </div>

    <br /><br />
   <table class="table table-hover table-striped">
       <thead class="table-dark">
       <tr>
           <th scope="col" class="text-center">Order Number</th>
           <th scope="col" class="text-center">Name</th>
           <th scope="col" class="text-center">Email</th>
           <th scope="col" class="text-center">Order Total</th>
           <th scope="col" class="text-center">PickUp Time</th>
           <th scope="col" class="text-center">Order Detail</th>
       </tr>
       </thead>
       <tbody class="table-secondary">
       @foreach (var item in Model.OrderList)
       {
           <tr>
               <td class="text-center align-middle">@item.OrderNumber</td>
               <td class="text-center align-middle">@item.Name</td>
               <td class="text-center align-middle">@item.Email</td>
               <td class="text-center align-middle">@item.OrderTotal</td>
               <td class="text-center align-middle">@item.PickupTime</td>
               <td class="text-center align-middle">
                   <a class="btn btn-outline-success ms-3 rounded-3" asp-page="/Order/OrderDetial" asp-route-OrderNumber="@item.OrderNumber">
                            <i class="bi bi-ticket-detailed-fill"></i>
                   </a>
               </td>
           </tr>
       }
       </tbody>
   </table>

</div>